-- MySQL Script generated by MySQL Workbench
-- Sun Nov 20 22:15:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`agência`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agência` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `salário_montante_total` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios` (
  `matricula` INT NOT NULL,
  `nome_completo` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `data_nasc` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  `cargo` ENUM('gerente', 'atendente', 'caixa') NOT NULL,
  `agência_id` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionarios_agência1_idx` (`agência_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_agência1`
    FOREIGN KEY (`agência_id`)
    REFERENCES `mydb`.`agência` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependentes` (
  `nome_completo` INT NOT NULL,
  `data_nasc` VARCHAR(45) NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  `funcionarios_matricula` INT NOT NULL,
  PRIMARY KEY (`nome_completo`),
  INDEX `fk_Dependentes_funcionarios1_idx` (`funcionarios_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Dependentes_funcionarios1`
    FOREIGN KEY (`funcionarios_matricula`)
    REFERENCES `mydb`.`funcionarios` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `cpf` INT(11) NOT NULL,
  `nome_completo` INT NOT NULL,
  `rg` INT(15) NOT NULL,
  `data_nasc` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  `orgao_emissor` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `nome_logradouro` VARCHAR(45) NOT NULL,
  `num_casa` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefones` (
  `telefone` INT(11) NOT NULL,
  `Contas_cpf` INT(11) NOT NULL,
  PRIMARY KEY (`telefone`, `Contas_cpf`),
  INDEX `fk_telefones_Contas_idx` (`Contas_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_Contas`
    FOREIGN KEY (`Contas_cpf`)
    REFERENCES `mydb`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emails` (
  `Contas_cpf` INT(11) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  INDEX `fk_Emails_Contas1_idx` (`Contas_cpf` ASC) VISIBLE,
  PRIMARY KEY (`Contas_cpf`, `email`),
  CONSTRAINT `fk_Emails_Contas1`
    FOREIGN KEY (`Contas_cpf`)
    REFERENCES `mydb`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contas` (
  `num_conta` INT NOT NULL,
  `agência_id` INT NOT NULL,
  `saldo` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo_conta` VARCHAR(45) NOT NULL,
  `conta_conjunta` TINYINT NOT NULL,
  `gerente_matricula` INT NOT NULL,
  PRIMARY KEY (`num_conta`),
  INDEX `fk_Contas_agência1_idx` (`agência_id` ASC) VISIBLE,
  INDEX `fk_Contas_funcionarios1_idx` (`gerente_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Contas_agência1`
    FOREIGN KEY (`agência_id`)
    REFERENCES `mydb`.`agência` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contas_funcionarios1`
    FOREIGN KEY (`gerente_matricula`)
    REFERENCES `mydb`.`funcionarios` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Poupanca` (
  `taxa_juros` INT NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`Contas_num_conta`),
  CONSTRAINT `fk_Poupanca_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `mydb`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especial` (
  `limite_credito` INT NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`Contas_num_conta`),
  CONSTRAINT `fk_Especial_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `mydb`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Corrente` (
  `data_aniver_contrato` INT NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`Contas_num_conta`),
  CONSTRAINT `fk_Corrente_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `mydb`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Possui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Possui` (
  `Clientes_cpf` INT(11) NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`Clientes_cpf`, `Contas_num_conta`),
  INDEX `fk_Clientes_has_Contas_Contas1_idx` (`Contas_num_conta` ASC) VISIBLE,
  INDEX `fk_Clientes_has_Contas_Clientes1_idx` (`Clientes_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_Contas_Clientes1`
    FOREIGN KEY (`Clientes_cpf`)
    REFERENCES `mydb`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_Contas_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `mydb`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tansacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tansacao` (
  `num_transacao` INT NOT NULL,
  `tipo_transacao` ENUM('saque', 'depósito', 'pagamento', 'estorno', 'transferência') NOT NULL,
  `data-hora` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`num_transacao`),
  INDEX `fk_Tansacao_Contas1_idx` (`Contas_num_conta` ASC) VISIBLE,
  CONSTRAINT `fk_Tansacao_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `mydb`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
