-- MySQL Script generated by MySQL Workbench
-- Fri Nov 25 16:10:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET SQL_SAFE_UPDATES = 0;
-- -----------------------------------------------------
-- Schema nullbank_469870
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nullbank_469870
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nullbank_469870` DEFAULT CHARACTER SET utf8 ;
USE `nullbank_469870` ;

-- -----------------------------------------------------
-- Table `nullbank_469870`.`Agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Agencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `salário_montante_total` DECIMAL(18,2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Funcionarios` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `data_nasc` DATE NOT NULL,
  `salario` DECIMAL(18,2) NOT NULL,
  `cargo` ENUM('gerente', 'atendente', 'caixa') NOT NULL,
  `agência_id` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionarios_agência1_idx` (`agência_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_agência1`
    FOREIGN KEY (`agência_id`)
    REFERENCES `nullbank_469870`.`Agencia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Dependentes` (
  `nome_completo` VARCHAR(45) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `funcionarios_matricula` INT NOT NULL,
  PRIMARY KEY (`nome_completo`),
  INDEX `fk_Dependentes_funcionarios1_idx` (`funcionarios_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Dependentes_funcionarios1`
    FOREIGN KEY (`funcionarios_matricula`)
    REFERENCES `nullbank_469870`.`Funcionarios` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Clientes` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome_completo` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(11) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  `orgao_emissor` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `nome_logradouro` VARCHAR(45) NOT NULL,
  `num_casa` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Telefones` (
  `telefone` VARCHAR(15) NOT NULL,
  `Contas_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`telefone`, `Contas_cpf`),
  INDEX `fk_telefones_Contas_idx` (`Contas_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_Contas`
    FOREIGN KEY (`Contas_cpf`)
    REFERENCES `nullbank_469870`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Emails` (
  `Contas_cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  INDEX `fk_Emails_Contas1_idx` (`Contas_cpf` ASC) VISIBLE,
  PRIMARY KEY (`Contas_cpf`, `email`),
  CONSTRAINT `fk_Emails_Contas1`
    FOREIGN KEY (`Contas_cpf`)
    REFERENCES `nullbank_469870`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Contas` (
  `num_conta` INT NOT NULL AUTO_INCREMENT,
  `agência_id` INT NOT NULL,
  `saldo` DECIMAL(18,2) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo_conta` ENUM('corrente', 'especial', 'poupanca') NOT NULL,
  `conta_conjunta` TINYINT NOT NULL,
  `gerente_matricula` INT NOT NULL,
  PRIMARY KEY (`num_conta`),
  INDEX `fk_Contas_agência1_idx` (`agência_id` ASC) VISIBLE,
  INDEX `fk_Contas_funcionarios1_idx` (`gerente_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Contas_agência1`
    FOREIGN KEY (`agência_id`)
    REFERENCES `nullbank_469870`.`Agencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contas_funcionarios1`
    FOREIGN KEY (`gerente_matricula`)
    REFERENCES `nullbank_469870`.`Funcionarios` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Poupanca` (
  `taxa_juros` FLOAT NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`Contas_num_conta`),
  CONSTRAINT `fk_Poupanca_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `nullbank_469870`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Especial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Especial` (
  `limite_credito` DECIMAL(18,2) NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`Contas_num_conta`),
  CONSTRAINT `fk_Especial_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `nullbank_469870`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Corrente` (
  `data_aniver_contrato` DATE NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`Contas_num_conta`),
  CONSTRAINT `fk_Corrente_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `nullbank_469870`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Possui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Possui` (
  `Clientes_cpf` VARCHAR(11) NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`Clientes_cpf`, `Contas_num_conta`),
  INDEX `fk_Clientes_has_Contas_Contas1_idx` (`Contas_num_conta` ASC) VISIBLE,
  INDEX `fk_Clientes_has_Contas_Clientes1_idx` (`Clientes_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_Contas_Clientes1`
    FOREIGN KEY (`Clientes_cpf`)
    REFERENCES `nullbank_469870`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Clientes_has_Contas_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `nullbank_469870`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nullbank_469870`.`Transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nullbank_469870`.`Transacao` (
  `num_transacao` INT NOT NULL AUTO_INCREMENT,
  `tipo_transacao` ENUM('saque', 'depósito', 'pagamento', 'estorno', 'transferência') NOT NULL,
  `data-hora` DATETIME NOT NULL,
  `valor` DECIMAL(18,2) NOT NULL,
  `Contas_num_conta` INT NOT NULL,
  PRIMARY KEY (`num_transacao`),
  INDEX `fk_Tansacao_Contas1_idx` (`Contas_num_conta` ASC) VISIBLE,
  CONSTRAINT `fk_Tansacao_Contas1`
    FOREIGN KEY (`Contas_num_conta`)
    REFERENCES `nullbank_469870`.`Contas` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- Criação do trigger responsável por cálculo da idade com base na data de nascimento
DROP TRIGGER IF EXISTS `nullbank_469870`.`tr_idade`;

DELIMITER $$
USE `nullbank_469870`$$
CREATE DEFINER = CURRENT_USER TRIGGER `nullbank_469870`.`tr_idade` BEFORE INSERT ON `dependentes` FOR EACH ROW
BEGIN
SET NEW.idade = TRUNCATE(DATEDIFF(CURDATE(), NEW.data_nasc)/365.25, 0);
END$$
DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
